version: 0.2
env:
  parameter-store:
    GITHUB_TOKEN: "GitHubPersonalToken"
phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - jar -cvf lambda/voice-translator-lambda.jar lambda/java-project/src/main/java/app/babelfish/LambdaHandler.java

  post_build:
    commands:
      - aws s3 cp lambda/voice-translator-lambda.jar s3://voice-translator-lambda/lambda/voice-translator-lambda.jar
      - aws s3 cp cloudformation/voice-translator.yaml s3://voice-translator-lambda/cloudformation/voice-translator.yaml
      - aws cloudformation create-change-set --change-set-type UPDATE --change-set-name voice-$(date +%F) --capabilities CAPABILITY_IAM --template-url https://voice-translator-lambda.s3.us-east-2.amazonaws.com/cloudformation/voice-translator.yaml --parameters ParameterKey=GitHubPersonalToken,ParameterValue=$GITHUB_TOKEN --stack-name voice
      - aws cloudformation update-stack --stack-name voice --capabilities CAPABILITY_IAM --parameters ParameterKey=GitHubPersonalToken,ParameterValue=$GITHUB_TOKEN --template-url https://voice-translator-lambda.s3.us-east-2.amazonaws.com/cloudformation/voice-translator.yaml