version: 0.2
phases:
  install:
    runtime-versions:
      runtime:
        java: openjdk11
  build:
    commands:
      - jar -cvf lambda/voice-translator-lambda.jar lambda/java-project/src/main/java/app/babelfish/LambdaHandler.java
  post_build:
    commands:
      - aws s3 cp lambda/voice-translator-lambda.jar s3://voice-translator-lambda/lambda/voice-translator-lambda.jar